import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '@styles/pages/pratice/Pratice.module.scss'

const Pratice: NextPage = () => {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Pratice</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>pratice</main>
    </div>
  )
}

export default Pratice
